uids <- c("A5A8LKqJw4w", "AakrBNBU2G4", "aFOYtl2chsD", "bGCtyadJhBd", 
          "bYF6imuLSgV", "c0dzFGFAZuO", "cObJTp3DWdY", "cRCw63EQEbM", 
          "czF2lzyXksI", "ectUGvYjtaK", "fg53NvKg3EN", "fpW7iq7zFNN", 
          "geh4jV9OIh7", "H7Iu1SBCLTm", "HOtmew3ZhxO", "hvtNfA73XhN", 
          "Hyvw9VnZ2ch", "iAYee99BIjX", "in0Xpzvlr33", "IvI3KbJILcD", 
          "IyKy3G6DbZ4", "JoERp5gZ6o1", "JuMoiYn1jKB", "K3I0l3A6fNt", 
          "kegCp8t3TVW", "KNgG5EHQ69Z", "KNO4emPfF91", "KPBucMJSdii", 
          "L2n6ajKliOT", "lAXeeoyddZd", "NWnZzJD94qO", "oREygLjW7vd", 
          "Os9GkOOHHJR", "ovQaECwOS1M", "PkVxxyOLky3", "qhGxKnmrZBd", 
          "QI0LrOAmBCG", "RGS21a5msis", "RhkU5KjtAi6", "RHN2Ui10Ivu", 
          "ScQASwweWXL", "SnpwfHHrqAu", "SpjvCpxnc20", "TjPwm5FAwoE", 
          "tUWykiXBnjC", "UossaY2RAd4", "vTXUgzE9cpS", "wkMmlftfTvx", 
          "XGCkcu1hrSo", "XuHtzXGDS00", "XwrgoYZOp6F", "Y5zUjJ7a5fK", 
          "YMfWvFuB5kH")
